[package]
name = "hnswlib"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.14.0"
rayon = "1.10.0"
rand = "0.8.5"

[build-dependencies]
cc = "1.2"
